
DROP TABLE IF EXISTS PERSON CASCADE;
CREATE TABLE PERSON(id SERIAL, uuid VARCHAR(200) UNIQUE NOT NULL, firstname VARCHAR(30) NOT NULL, lastname VARCHAR(30) ,email VARCHAR(50),
                      contact_number VARCHAR(30) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255)  ,PRIMARY KEY(id));

DROP TABLE IF EXISTS ACCOUNT CASCADE;
CREATE TABLE ACCOUNT(id SERIAL, account_number VARCHAR(200) UNIQUE NOT NULL,account_type VARCHAR(255), balance INTEGER,  pid INTEGER, PRIMARY KEY (id),FOREIGN KEY (pid) REFERENCES PERSON(id));

DROP TABLE IF EXISTS STATEMENT CASCADE;
CREATE TABLE STATEMENT(id SERIAL,reference_number VARCHAR(200) UNIQUE NOT NULL, debit INTEGER, credit INTEGER , date DATE, aid INTEGER, balance INTEGER, PRIMARY KEY (id), FOREIGN KEY (aid) REFERENCES ACCOUNT(id));

DROP TABLE IF EXISTS CUSTOMER_AUTH CASCADE;
CREATE TABLE CUSTOMER_AUTH(id SERIAL,uuid VARCHAR(200) UNIQUE NOT NULL, customer_id INTEGER NOT NULL, access_token VARCHAR(500), login_at TIMESTAMP, logout_at TIMESTAMP,expires_at TIMESTAMP, PRIMARY KEY (id), FOREIGN KEY (customer_id) REFERENCES PERSON(id) ON DELETE CASCADE);

